<a href="https://colab.research.google.com/github/gr-sajib01/FirstL043/blob/main/Data%20processind%20task%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dataset.csv to Dataset.csv

In [3]:
import pandas as pd
df=pd.read_csv("Dataset.csv")
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,999999
2,female,group B,master's degree,standard,none,90,95,NaN,278
3,male,group A,associate's degree,free/reduced,none,NaN,57,-999,148
4,male,group C,some college,standard,NaN,76,-999,75,229

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gender                       909 non-null    object
 1   Race/ethnicity               906 non-null    object
 2   Parental level of education  905 non-null    object
 3   Lunch                        904 non-null    object
 4   Test preparation course      903 non-null    object
 5   Math score                   910 non-null    object
 6   Reading score                903 non-null    object
 7   Writing score                913 non-null    object
 8   Total Score                  912 non-null    object
dtypes: object(9)
memory usage: 70.5+ KB

In [5]:
df=df.drop_duplicates()
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,999999
2,female,group B,master's degree,standard,none,90,95,NaN,278
3,male,group A,associate's degree,free/reduced,none,NaN,57,-999,148
4,male,group C,some college,standard,NaN,76,-999,75,229

In [8]:
df.replace(999999,None,inplace=True)
df.replace(-999,None,inplace=True)
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,999999
2,female,group B,master's degree,standard,none,90,95,NaN,278
3,male,group A,associate's degree,free/reduced,none,NaN,57,-999,148
4,male,group C,some college,standard,NaN,76,-999,75,229

In [11]:
df["Math score"] = pd.to_numeric(df["Math score"], errors="coerce")

In [12]:
df = df[(df["Math score"] <= 100) & (df["Math score"] >= 0)]

In [14]:
df = df[(df["Math score"] <= 100) & (df["Math score"] >= 0)]
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72.0,72,74,218
1,female,group C,some college,standard,completed,69.0,90,88,999999
2,female,group B,master's degree,standard,none,90.0,95,NaN,278
4,male,group C,some college,standard,NaN,76.0,-999,75,229
5,qajpPq,group B,associate's degree,standard,none,71.0,83,78,232

In [15]:
sample_df=df.sample(n=50)
sample_df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
228,male,lK2V0z,some high school,free/reduced,none,68.0,72,64,204
711,female,group E,some high school,standard,zGZkOa,80.0,85,85,250
965,female,group D,some college,TldOs7,none,62.0,70,72,204
308,female,group B,associate's degree,free/reduced,none,53.0,71,67,191
770,male,group B,high school,standard,none,52.0,NaN,-999,149

In [18]:
cols = ["Math score", "Reading score", "Writing score"]
for c in cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

In [19]:
df["Total Score"] = df["Math score"] + df["Reading score"] + df["Writing score"]

In [21]:
df["Total Score"] = df["Math score"] + df["Reading score"] + df["Writing score"]
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72.0,72.0,74.0,218.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0
2,female,group B,master's degree,standard,none,90.0,95.0,NaN,NaN
4,male,group C,some college,standard,NaN,76.0,-999.0,75.0,-848.0
5,qajpPq,group B,associate's degree,standard,none,71.0,83.0,78.0,232.0

In [22]:
df = df.dropna()

In [23]:
df.head()

,Gender,Race/ethnicity,Parental level of education,Lunch,Test preparation course,Math score,Reading score,Writing score,Total Score
0,qajpPq,group B,bachelor's degree,standard,zGZkOa,72.0,72.0,74.0,218.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0
5,qajpPq,group B,associate's degree,standard,none,71.0,83.0,78.0,232.0
8,male,group D,high school,free/reduced,completed,64.0,64.0,67.0,195.0
10,male,group C,associate's degree,standard,none,58.0,54.0,52.0,164.0

In [25]:
df.to_csv("clean_dataset.csv",index=False)